-- BDTravel Supabase / PostgreSQL schema
-- Run this in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  home_district text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.districts (
  id bigint generated by default as identity primary key,
  name text not null unique,
  division text not null,
  official_portal text,
  directory_status text,
  attractions_status text,
  live_poi_status text
);

create table if not exists public.tourist_spots (
  id bigint generated by default as identity primary key,
  district_id bigint references public.districts(id) on delete cascade,
  district text not null,
  name text not null,
  coordinates text,
  best_season text,
  estimated_cost_bdt_per_person text,
  activities text,
  food text,
  hotel text,
  transport text,
  safety text,
  nearby_hospital text,
  data_status text,
  source_note text
);

create table if not exists public.wishlist (
  user_id uuid references auth.users(id) on delete cascade,
  destination_name text not null,
  created_at timestamptz not null default now(),
  primary key (user_id, destination_name)
);

create table if not exists public.travel_passport (
  user_id uuid references auth.users(id) on delete cascade,
  district_id bigint references public.districts(id) on delete cascade,
  visited_at timestamptz not null default now(),
  primary key (user_id, district_id)
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  destination_name text not null,
  rating integer not null check (rating between 1 and 5),
  review_text text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.photos (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  destination_name text,
  caption text,
  image_url text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.trips (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  title text,
  days integer,
  travellers integer,
  budget_bdt numeric,
  travel_type text,
  itinerary jsonb,
  created_at timestamptz not null default now()
);

-- Row Level Security
alter table public.profiles enable row level security;
alter table public.districts enable row level security;
alter table public.tourist_spots enable row level security;
alter table public.wishlist enable row level security;
alter table public.travel_passport enable row level security;
alter table public.reviews enable row level security;
alter table public.photos enable row level security;
alter table public.trips enable row level security;

-- Public catalogue
create policy "districts public read" on public.districts for select using (true);
create policy "tourist spots public read" on public.tourist_spots for select using (true);
create policy "reviews public read" on public.reviews for select using (true);
create policy "photos public read" on public.photos for select using (true);

-- Own user data
create policy "profile own access" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "wishlist own access" on public.wishlist for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "passport own access" on public.travel_passport for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "trip own access" on public.trips for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "reviews authenticated insert" on public.reviews for insert to authenticated with check (auth.uid() = user_id);
create policy "reviews own update" on public.reviews for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "reviews own delete" on public.reviews for delete using (auth.uid() = user_id);
create policy "photos authenticated insert" on public.photos for insert to authenticated with check (auth.uid() = user_id);
create policy "photos own delete" on public.photos for delete using (auth.uid() = user_id);

-- Storage bucket for community photos
insert into storage.buckets (id, name, public) values ('community-photos', 'community-photos', true)
on conflict (id) do nothing;

create policy "community photos public read" on storage.objects for select using (bucket_id = 'community-photos');
create policy "community photos authenticated upload" on storage.objects for insert to authenticated with check (bucket_id = 'community-photos' and auth.uid()::text = (storage.foldername(name))[1]);
create policy "community photos own delete" on storage.objects for delete to authenticated using (bucket_id = 'community-photos' and auth.uid()::text = (storage.foldername(name))[1]);

-- Auto-create a profile when a new auth user is created.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, name) values (new.id, coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
